#' Download NASA NEX-GDDP-CMIP6 data from Amazon Web Services
#'
#' Use this function if you want to download NASA NEX-GDDP-CMIP6 data for the
#' entire globe. Called via [`cmip6_dl`] when no area of interest
#' (`aoi`) is specified.
#'
#' @param plan A [`tibble::tbl_df`] filtering data from [`cmip6_ls`] that
#' contains the data to be downloaded. Generated by [`cmip6_dl`].
#' @inherit cmip6_dl params return
cmip6_dl_aws <-
  function(
      plan,
      outdir,
      workers,
      force) {
    # Checks
    checkmate::assert_data_frame(plan)
    checkmate::assert_directory_exists(outdir)
    checkmate::assert_int(workers)
    checkmate::assert_logical(force)

    clust <- multidplyr::new_cluster(workers)
    multidplyr::cluster_library(clust, c("magrittr"))
    multidplyr::cluster_copy(clust, c("download_file", "force"))

    out <-
      plan |>
      dplyr::mutate(
        file =
          file.path(
            outdir,
            dataset
          ),
        url =
          file.path(
            "https://nex-gddp-cmip6.s3-us-west-2.amazonaws.com",
            path
          )
      ) |>
      dplyr::rowwise() |>
      multidplyr::partition(clust) |>
      dplyr::mutate(
        file =
          download_file(
            url = url,
            out.path = file,
            force = force
          )
      ) |>
      dplyr::collect() |>
      dplyr::arrange(model, scenario, run, element, year, version)

    rm(clust)

    return(out)
  }
