#' Download NASA NEX-GDDP-CMIP6 data from the NCCS THREDDS Data Catalog
#'
#' Use this function if you want to download NASA NEX-GDDP-CMIP6 data for a
#' specific area of interest (`aoi`). Called via [`cmip6_dl`] when an
#' `aoi` is specified.
#'
#' @param plan A [`tibble::tbl_df`] filtering data from [`cmip6_ls`] that
#' contains the data to be downloaded. Generated by [`cmip6_dl`].
#' @inherit cmip6_dl params return
cmip6_dl_tds <-
  function(
      aoi,
      plan,
      outdir,
      workers,
      force) {
    # Checks
    checkmate::assert_class(aoi, "sf")
    checkmate::assert_data_frame(plan)
    checkmate::assert_directory_exists(outdir)
    checkmate::assert_int(workers)
    checkmate::assert_logical(force)

    aoi <-
      aoi |>
      sf::st_transform(4326) |>
      st_rotate() |>
      sf::st_bbox() |>
      as.list()

    clust <- multidplyr::new_cluster(workers)
    multidplyr::cluster_library(clust, "magrittr")
    multidplyr::cluster_copy(clust, c("download_file", "force"))

    out <-
      plan |>
      dplyr::rowwise() |>
      dplyr::mutate(
        file =
          file.path(
            outdir,
            dataset
          ),
        url =
          (
            httr2::request(
              file.path(
                "https://ds.nccs.nasa.gov/thredds/ncss/grid/AMES",
                sub(
                  pattern = "NEX-GDDP-CMIP6",
                  replacement = "NEX/GDDP-CMIP6",
                  x = path
                )
              )
            ) |>
              httr2::req_url_query(
                var = element,
                north = aoi$ymax,
                west = aoi$xmin,
                east = aoi$xmax,
                south = aoi$ymin,
                disableProjSubset = "on",
                horizStride = 1,
                time_start = paste0(year, "-01-01"),
                time_end = paste0(as.integer(year) + 1, "-01-01"),
                timeStride = 1,
                addLatLon = TRUE
              )
          )$url
      ) |>
      multidplyr::partition(clust) |>
      dplyr::mutate(
        file =
          download_file(
            url = url,
            out.path = file,
            force = force
          )
      ) |>
      dplyr::collect() |>
      dplyr::arrange(model, scenario, run, element, year, version)

    rm(clust)

    return(out)
  }
